Fix pd Series related issue, seeminly due to pd and/or python version
- Fix for 'AttributeError: 'Series' object has no attribute 'reshape'
Use values before reashape as suggested the following link
https://stackoverflow.com/questions/53723928/attributeerror-series-object-has-no-attribute-reshape
- use numpy ndarray to sum, otherwise pd sum's generates non sclar
  errors

- running environment

```
numpy==1.19.1
pandas==1.1.0
python==3.7

```